Nom : 
- AGBOSSOU SESSOU Hola Anne-Stéphanie
- DUEVI-TSIBIAKU koko Bertille

Filère : IA et Big Data

# Etape 1 : Chargement des données

In [1]:
import pandas as pd

In [2]:
def load_data(file_path : str):
    return pd.read_csv(file_path)

load_data('transactions.csv')

,global_id,sender_id,receiver_id,initial_amount,transfer_amount,amount_received,final_amount,date
0,1,417,583,102.332066,11.004279,11.004279,91.327787,2021-10-07 12:16:55.521706
1,2,68,277,83.130697,6.325441,6.325441,76.805256,2023-08-16 00:26:54.521999
2,3,621,546,96.091707,2.435575,2.435575,93.656132,2024-03-26 11:50:51.518583
3,4,783,337,82.476615,13.056381,13.056381,69.420234,2025-01-30 13:57:10.355813
4,5,255,327,92.090839,19.036857,19.036857,73.053982,2020-06-13 12:35:59.742668
...,...,...,...,...,...,...,...,...
19995,19996,1009,878,286874.286599,38944.934502,38944.934502,247929.352097,2023-09-05 09:24:29.964619
19996,19997,1009,395,161666.115393,29830.844765,29830.844765,131835.270628,2024-10-23 11:18:44.129803
19997,19998,1009,782,147024.204132,26231.674099,26231.674099,120792.530033,2024-06-28 03:06:30.528322
19998,19999,1009,516,177350.875490,26754.251248,26754.251248,150596.624242,2023-07-11 12:29:22.930733
19999,20000,1009,705,238052.566635,20089.998871,20089.998871,217962.567764,2024-10-05 17:15:34.302602

In [3]:
df_transaction = load_data('transactions.csv')
df_transaction.head()

,global_id,sender_id,receiver_id,initial_amount,transfer_amount,amount_received,final_amount,date
0,1,417,583,102.332066,11.004279,11.004279,91.327787,2021-10-07 12:16:55.521706
1,2,68,277,83.130697,6.325441,6.325441,76.805256,2023-08-16 00:26:54.521999
2,3,621,546,96.091707,2.435575,2.435575,93.656132,2024-03-26 11:50:51.518583
3,4,783,337,82.476615,13.056381,13.056381,69.420234,2025-01-30 13:57:10.355813
4,5,255,327,92.090839,19.036857,19.036857,73.053982,2020-06-13 12:35:59.742668

# Etape 2 : Sélection des caractéristiques pertinentes

In [4]:
# les colonnes utiles pour la détection d’anomalies

def select_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Select relevant numerical features for clustering.
    """
    features = [
        "initial_amount",
        "transfer_amount",
        "amount_received",
        "final_amount"
    ]
    
    return df[features]


df_features = select_features(df_transaction)
df_features.head()

   initial_amount  transfer_amount  amount_received  final_amount
0      102.332066        11.004279        11.004279     91.327787
1       83.130697         6.325441         6.325441     76.805256
2       96.091707         2.435575         2.435575     93.656132
3       82.476615        13.056381        13.056381     69.420234
4       92.090839        19.036857        19.036857     73.053982